["pca\addons\suture\functions\fnc_sutureStart.sqf", "pca_suture_fnc_sutureStart"] call CBA_fnc_compileFunction;
["pca\addons\suture\functions\fnc_clearCache.sqf", "pca_suture_fnc_clearCache"] call CBA_fnc_compileFunction;
["pca\addons\suture\functions\fnc_showCount.sqf", "pca_suture_fnc_showCount"] call CBA_fnc_compileFunction;
["pca\addons\suture\functions\fnc_canSuture.sqf", "pca_suture_fnc_canSuture"] call CBA_fnc_compileFunction;
["pca\addons\suture\functions\fnc_diagnose.sqf", "pca_suture_fnc_diagnose"] call CBA_fnc_compileFunction;
["pca\addons\suture\functions\fnc_checkPulse.sqf", "pca_suture_fnc_checkPulse"] call CBA_fnc_compileFunction;
["pca\addons\suture\functions\fnc_CheckBloodPressure.sqf", "pca_suture_fnc_CheckBloodPressure"] call CBA_fnc_compileFunction;
["pca\addons\suture\functions\fnc_CheckResponse.sqf", "pca_suture_fnc_CheckResponse"] call CBA_fnc_compileFunction;
["pca\addons\suture\functions\fnc_autoTriage.sqf", "pca_suture_fnc_autoTriage"] call CBA_fnc_compileFunction;